### ISSUE TITLE
background color for screens?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder-basics#12]
After our experience in https://github.com/phetsims/graphing-slope-intercept/issues/11, do we want to use a different background color in this sim, to differentiate it from Function Builder?

**Comment by amanda-phet** [comment]
Yes, we definitely want to do this, especially since the screenshots will look similar (because we used the Patterns screen for the Function Builder screenshot!). 

It's such a colorful screen, I'm not sure what would make sense yet, but I"ll play with colors a bit. Perhaps this light blue (E1F7FF) could work. @pixelzoom let's go with this for now and unless anyone objects we can close the issue. 

![screen shot 2017-04-12 at 3 42 34 pm](https://cloud.githubusercontent.com/assets/7852916/24980728/b7768a4e-1f96-11e7-8804-85876dea62e8.png)

**Comment by pixelzoom** [comment]
@amanda-phet Do you also want a different color for the Mystery screen?

**Comment by pixelzoom** [comment]
Here's a dev version with the blue Patterns screen:
http://www.colorado.edu/physics/phet/dev/html/function-basics/1.0.0-dev.1/function-basics_en.html

Let me know if you want to change the Mystery screen.

**Comment by pixelzoom** [comment]
I realized that I hadn't changed the background on the Patterns screen icon.  That's done in the above commit, but not in 1.0.0-dev.1.  Here's a screenshot of how it looks:

![screenshot_213](https://cloud.githubusercontent.com/assets/3046552/24985624/a6523512-1fb2-11e7-926d-f9efc75fa980.png)

**Comment by pixelzoom** [comment]
4/13/17 design meeting:

• revert color of Patterns screen
• no new color for Mystery screen
• new screenshot for Function Builder, use Numbers screen (see https://github.com/phetsims/function-builder/issues/106)

**Comment by pixelzoom** [comment]
Background color reverted. Closing.
