### ISSUE TITLE
create screenshot

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder-basics#13]

**Comment by amanda-phet** [comment]
We discussed using the same screenshot that is currently being used for Function Builder, since it highlights the Patterns screen. It will just need to be redone since the navbar is different. 

This is what it should look like (but use Function Basics to create it!): 

![function-builder-600](https://cloud.githubusercontent.com/assets/7852916/25021962/53e396b4-2051-11e7-9e78-2b56cadc3edb.png)

**Comment by pixelzoom** [comment]
@phet-steele Could you please create this screenshot, as shown above?  Check in to master only, and use this dev version:

**Comment by pixelzoom** [comment]
@phet-steele Could you please create this screenshot, as shown above? Check in to master only, and use this dev version:

http://www.colorado.edu/physics/phet/dev/html/function-builder-basics/1.0.0-dev.2/function-builder-basics_en.html

Notes the card (cherries) that is partially inserted into the builder's input slot.

**Comment by phet-steele** [comment]
@pixelzoom, done above. Back to you.

**Comment by pixelzoom** [comment]
Verified, thank you @phet-steele. Closing.
